export const CREATE_RATING_REQUEST = "CREATE_RATING_REQUEST";
export const CREATE_RATING_SUCCESS = "CREATE_RATING_SUCCESS";
export const CREATE_RATING_FAILURE = "CREATE_RATING_FAILURE";

export const GET_ALL_RATING_REQUEST = "GET_ALL_RATING_REQUEST";
export const GET_ALL_RATING_SUCCESS = "GET_ALL_RATING_SUCCESS";
export const GET_ALL_RATING_FAILURE = "GET_ALL_RATING_FAILURE";

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAILURE = "CREATE_REVIEW_FAILURE";

export const GET_ALL_REVIEW_REQUEST = "GET_ALL_REVIEW_REQUEST";
export const GET_ALL_REVIEW_SUCCESS = "GET_ALL_REVIEW_SUCCESS";
export const GET_ALL_REVIEW_FAILURE = "GET_ALL_REVIEW_FAILURE";
